default: &default
  adapter: postgresql
  encoding: unicode
  database: blog_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: admin
  password: admin
  timeout: 5000

development:
  <<: *default
  database: blog_db_dev

test:
  <<: *default
  database: blog_db_test
